Fix schema manager when filter is not set.
- Get all tables from all database when filter is not set.
- The hardcoded schema json for retrieveSchema method did
not work. However, unittest does not pass with error
org.apache.avro.UnresolvedUnionException: Not in union ["null","int"]: 0 (field=DECIMAL_DIGITS)
So, I chose a test case where the DECIMAL_DIGITS is null. This seems
like an avro bug.

b/190213436

Change-Id: I4735017fa3041c94c6202e9d479561105449bf8f